// REPOSITORIES
export const INJECTION_REPOSITORY_ADDRESS = '@INJECTION_REPOSITORY_ADDRESS';

// USE CASES
export const INJECTION_USECASE_CREATE_ADDRESS =
  '@INJECTION_USECASE_CREATE_ADDRESS';
export const INJECTION_USECASE_UPDATE_ADDRESS =
  '@INJECTION_USECASE_UPDATE_ADDRESS';
export const INJECTION_USECASE_DELETE_ADDRESS =
  '@INJECTION_USECASE_DELETE_ADDRESS';
export const INJECTION_USECASE_FIND_BY_ADDRESS =
  '@INJECTION_USECASE_FIND_BY_ADDRESS';
export const INJECTION_USECASE_FIND_ALL_ADDRESS =
  '@INJECTION_USECASE_FIND_ALL_ADDRESS';

// SERVICES
export const INJECTION_SERVICE_CREATE_ADDRESS =
  '@INJECTION_SERVICE_CREATE_ADDRESS';
export const INJECTION_SERVICE_UPDATE_ADDRESS =
  '@INJECTION_SERVICE_UPDATE_ADDRESS';
export const INJECTION_SERVICE_DELETE_ADDRESS =
  '@INJECTION_SERVICE_DELETE_ADDRESS';
export const INJECTION_SERVICE_FIND_BY_ADDRESS =
  '@INJECTION_SERVICE_FIND_BY_ADDRESS';
export const INJECTION_SERVICE_FIND_ALL_ADDRESS =
  '@INJECTION_SERVICE_FIND_ALL_ADDRESS';
