// REPOSITORIES
export const INJECTION_REPOSITORY_USER = '@INJECTION_REPOSITORY_USER';

//SERVICES
export const INJECTION_SERVICE_CREATE_USER = '@INJECTION_SERVICE_CREATE_USER';
export const INJECTION_SERVICE_UPDATE_USER = '@INJECTION_SERVICE_UPDATE_USER';
export const INJECTION_SERVICE_FIND_ALL_USER =
  '@INJECTION_SERVICE_FIND_ALL_USER';
export const INJECTION_SERVICE_FIND_BY_USER = '@INJECTION_SERVICE_FIND_BY_USER';
export const INJECTION_SERVICE_DELETE_USER = '@INJECTION_SERVICE_DELETE_USER';
export const INJECTION_SERVICE_AUTH = '@INJECTION_SERVICE_AUTH';

// USE CASES
export const INJECTION_USECASE_CREATE_USER = '@INJECTION_USECASE_CREATE_USER';
export const INJECTION_USECASE_UPDATE_USER = '@INJECTION_USECASE_UPDATE_USER';
export const INJECTION_USECASE_DELETE_USER = '@INJECTION_USECASE_DELETE_USER';
export const INJECTION_USECASE_FIND_BY_USER = '@INJECTION_USECASE_FIND_BY_USER';
export const INJECTION_USECASE_FIND_ALL_USER =
  '@INJECTION_USECASE_FIND_ALL_USER';
